# Hugo配置
# 使用指南：https://docs.hugoblox.com/tutorial/
# Hugo官方文档：https://gohugo.io/getting-started/configuration/#all-configuration-settings
# 本配置文件采用YAML语法格式 - 参见：https://learnxinyminutes.com/docs/yaml/

# 网站名称
title: Passion4ever
# 网站网址
baseURL: 'https://example.com/'

############################
## 语言
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## 高级
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
