# 语言
#   为您的每种网站语言创建一个独立版块。
#   文档地址：https://docs.hugoblox.com/reference/language/

# 默认语言
en:
  languageCode: en-us
  # 若需支持多语言站点，请取消注释，并将英文内容移至 `en` 子文件夹。
  #contentDir: content/en

# 取消下面几行的注释，可以设置你的网站的第二种语言。
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
