# 导航链接
# 要链接至首页小部件，请将URL指定为井号`#`后接所需部件在`content/home/`目录下的文件名。

# weight参数用于定义链接在页面上出现的顺序排列。

main:
  - name: Home
    url: /
    weight: 10
  - name: Publications
    url: publications/
    weight: 20
  - name: Blogs
    url: posts/
    weight: 30